#
# Vivado (TM) v2015.2 (64-bit)
#
# build-project-2.tcl: Tcl script for re-creating project 'glitc-project'
#
# Generated by Vivado on Mon Oct 26 15:20:25 -0400 2015
# IP Build 1264090 on Wed Jun 24 14:22:01 MDT 2015
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (build-project-2.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/common/RITC_bit_control.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/GLITC_external_settings/opencores_i2c/i2c_master_defines.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/GLITC_external_settings/opencores_i2c/i2c_master_bit_ctrl.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/RITC_full_datapath/vcdl_1_wrapper_v2.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/RITC_full_datapath/vcdl_0_wrapper_v2.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/RITC_full_datapath/RITC_bit_control_loader.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/RITC_full_datapath/glitc_clock_path_wrapper.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/common/flag_sync.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/dual_RITC_correlator/correlator/carry_save_adder.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/dual_RITC_correlator/correlator/lsb_adder.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/dual_RITC_correlator/correlator/six_bit_sum_power.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/GLITC_external_settings/opencores_i2c/i2c_master_byte_ctrl.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/RITC_full_datapath/RITC_vcdl.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/RITC_full_datapath/RITC_datapath_control.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/RITC_full_datapath/GLITC_refclk_counters.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/RITC_full_datapath/glitc_data_path_wrapper_v2.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/RITC_full_datapath/GLITC_datapath_buffers_v2.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/RITC_full_datapath/glitc_clock_path_wrapper_v2.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/RITC_full_datapath/dsp_accumulator_mux.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/dual_RITC_correlator/RITC_sample_storage_address_generator.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/dual_RITC_correlator/RITC_sample_memory.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/dual_RITC_correlator/fabric_compare_4.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/dual_RITC_correlator/correlator/RITC_dynamic_corrector_v3.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/dual_RITC_correlator/correlator/quad_dsp_sum.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/dual_RITC_correlator/correlator/partition_and_preadd_v8.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/dual_RITC_correlator/correlator/add_and_square_v8.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/glitc_intercom/glitc_intercom_iserdes_and_sync.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/dual_RITC_correlator/RITC_input_channel_storage.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/RITC_dual_phase_scanner/ritc_phase_scan_program_V3.vhd"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/RITC_dual_phase_scanner/RITC_phase_scanner_registers_v4.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/GLITC_external_settings/opencores_i2c/i2c_master_top.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/GLITC_external_settings/glitc_external_settings_rom.vhd"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/RITC_full_datapath/RITC_dual_input_buffers.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/RITC_full_datapath/RITC_dual_datapath_v3.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/common/kcpsm6.vhd"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/GLITC_clock_generator/GLITC_clock_realigner.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/dual_RITC_correlator/RITC_sample_storage_v2.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/dual_RITC_correlator/RITC_input_storage_v2.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/dual_RITC_correlator/RITC_compare_tree_by4.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/dual_RITC_correlator/correlator/quad_corr_v11.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/glitc_intercom/glitc_intercom_training.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/glitc_intercom/glitc_intercom_sync_generator.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/glitc_intercom/glitc_intercom_oserdes_v2.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/glitc_intercom/glitc_intercom_iserdes_v2.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/glitc_intercom/glitc_intercom_input_buffers.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/glitc_intercom/glitc_intercom_echo_handler.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/glitc_intercom/glitc_intercom_control.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/GLITC_control_registers.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/glitcbus_slave_v2.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/glitc_debug_mux.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/glitcbus_clock.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/RITC_Dual_DAC/RITC_Dual_DAC.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/RITC_dual_phase_scanner/RITC_dual_phase_scanner_v3.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/GLITC_external_settings/GLITC_external_settings.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/RITC_full_datapath/RITC_full_datapath_v2.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/GLITC_clock_generator/GLITC_clock_generator.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/dual_RITC_correlator/dual_RITC_correlator_v3.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/glitc_intercom/glitc_intercom_v3.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/ip_cores/glitc_icon/glitc_icon.xco"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/ip_cores/glitc_ila/glitc_ila.xco"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/ip_cores/glitc_vio/glitc_vio.xco"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/glitc_top_v2.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/RITC_dual_phase_scanner/ROM_form.vhd"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/GLITC_external_settings/ROM_form.vhd"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/hdl/GLITC_external_settings/opencores_i2c/timescale.v"
#    "C:/cygwin/home/barawn/repositories/github/firmware-glitc/constraints/glitc_top_v2.xdc"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/glitc-project"]"

# Create project
create_project glitc-project ./glitc-project

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [get_projects glitc-project]
set_property "default_lib" "xil_defaultlib" $obj
set_property "part" "xc7a200tfbg484-2" $obj
set_property "simulator_language" "Mixed" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hdl/common/RITC_bit_control.v"]"\
 "[file normalize "$origin_dir/hdl/GLITC_external_settings/opencores_i2c/i2c_master_defines.v"]"\
 "[file normalize "$origin_dir/hdl/GLITC_external_settings/opencores_i2c/i2c_master_bit_ctrl.v"]"\
 "[file normalize "$origin_dir/hdl/RITC_full_datapath/vcdl_1_wrapper_v2.v"]"\
 "[file normalize "$origin_dir/hdl/RITC_full_datapath/vcdl_0_wrapper_v2.v"]"\
 "[file normalize "$origin_dir/hdl/RITC_full_datapath/RITC_bit_control_loader.v"]"\
 "[file normalize "$origin_dir/hdl/RITC_full_datapath/glitc_clock_path_wrapper.v"]"\
 "[file normalize "$origin_dir/hdl/common/flag_sync.v"]"\
 "[file normalize "$origin_dir/hdl/dual_RITC_correlator/correlator/carry_save_adder.v"]"\
 "[file normalize "$origin_dir/hdl/dual_RITC_correlator/correlator/lsb_adder.v"]"\
 "[file normalize "$origin_dir/hdl/dual_RITC_correlator/correlator/six_bit_sum_power.v"]"\
 "[file normalize "$origin_dir/hdl/GLITC_external_settings/opencores_i2c/i2c_master_byte_ctrl.v"]"\
 "[file normalize "$origin_dir/hdl/RITC_full_datapath/RITC_vcdl.v"]"\
 "[file normalize "$origin_dir/hdl/RITC_full_datapath/RITC_datapath_control.v"]"\
 "[file normalize "$origin_dir/hdl/RITC_full_datapath/GLITC_refclk_counters.v"]"\
 "[file normalize "$origin_dir/hdl/RITC_full_datapath/glitc_data_path_wrapper_v2.v"]"\
 "[file normalize "$origin_dir/hdl/RITC_full_datapath/GLITC_datapath_buffers_v2.v"]"\
 "[file normalize "$origin_dir/hdl/RITC_full_datapath/glitc_clock_path_wrapper_v2.v"]"\
 "[file normalize "$origin_dir/hdl/RITC_full_datapath/dsp_accumulator_mux.v"]"\
 "[file normalize "$origin_dir/hdl/dual_RITC_correlator/RITC_sample_storage_address_generator.v"]"\
 "[file normalize "$origin_dir/hdl/dual_RITC_correlator/RITC_sample_memory.v"]"\
 "[file normalize "$origin_dir/hdl/dual_RITC_correlator/fabric_compare_4.v"]"\
 "[file normalize "$origin_dir/hdl/dual_RITC_correlator/correlator/RITC_dynamic_corrector_v3.v"]"\
 "[file normalize "$origin_dir/hdl/dual_RITC_correlator/correlator/quad_dsp_sum.v"]"\
 "[file normalize "$origin_dir/hdl/dual_RITC_correlator/correlator/partition_and_preadd_v8.v"]"\
 "[file normalize "$origin_dir/hdl/dual_RITC_correlator/correlator/add_and_square_v8.v"]"\
 "[file normalize "$origin_dir/hdl/glitc_intercom/glitc_intercom_iserdes_and_sync.v"]"\
 "[file normalize "$origin_dir/hdl/dual_RITC_correlator/RITC_input_channel_storage.v"]"\
 "[file normalize "$origin_dir/hdl/RITC_dual_phase_scanner/ritc_phase_scan_program_V3.vhd"]"\
 "[file normalize "$origin_dir/hdl/RITC_dual_phase_scanner/RITC_phase_scanner_registers_v4.v"]"\
 "[file normalize "$origin_dir/hdl/GLITC_external_settings/opencores_i2c/i2c_master_top.v"]"\
 "[file normalize "$origin_dir/hdl/GLITC_external_settings/glitc_external_settings_rom.vhd"]"\
 "[file normalize "$origin_dir/hdl/RITC_full_datapath/RITC_dual_input_buffers.v"]"\
 "[file normalize "$origin_dir/hdl/RITC_full_datapath/RITC_dual_datapath_v3.v"]"\
 "[file normalize "$origin_dir/hdl/common/kcpsm6.vhd"]"\
 "[file normalize "$origin_dir/hdl/GLITC_clock_generator/GLITC_clock_realigner.v"]"\
 "[file normalize "$origin_dir/hdl/dual_RITC_correlator/RITC_sample_storage_v2.v"]"\
 "[file normalize "$origin_dir/hdl/dual_RITC_correlator/RITC_input_storage_v2.v"]"\
 "[file normalize "$origin_dir/hdl/dual_RITC_correlator/RITC_compare_tree_by4.v"]"\
 "[file normalize "$origin_dir/hdl/dual_RITC_correlator/correlator/quad_corr_v11.v"]"\
 "[file normalize "$origin_dir/hdl/glitc_intercom/glitc_intercom_training.v"]"\
 "[file normalize "$origin_dir/hdl/glitc_intercom/glitc_intercom_sync_generator.v"]"\
 "[file normalize "$origin_dir/hdl/glitc_intercom/glitc_intercom_oserdes_v2.v"]"\
 "[file normalize "$origin_dir/hdl/glitc_intercom/glitc_intercom_iserdes_v2.v"]"\
 "[file normalize "$origin_dir/hdl/glitc_intercom/glitc_intercom_input_buffers.v"]"\
 "[file normalize "$origin_dir/hdl/glitc_intercom/glitc_intercom_echo_handler.v"]"\
 "[file normalize "$origin_dir/hdl/glitc_intercom/glitc_intercom_control.v"]"\
 "[file normalize "$origin_dir/hdl/GLITC_control_registers.v"]"\
 "[file normalize "$origin_dir/hdl/glitcbus_slave_v2.v"]"\
 "[file normalize "$origin_dir/hdl/glitc_debug_mux.v"]"\
 "[file normalize "$origin_dir/hdl/glitcbus_clock.v"]"\
 "[file normalize "$origin_dir/hdl/RITC_Dual_DAC/RITC_Dual_DAC.v"]"\
 "[file normalize "$origin_dir/hdl/RITC_dual_phase_scanner/RITC_dual_phase_scanner_v3.v"]"\
 "[file normalize "$origin_dir/hdl/GLITC_external_settings/GLITC_external_settings.v"]"\
 "[file normalize "$origin_dir/hdl/RITC_full_datapath/RITC_full_datapath_v2.v"]"\
 "[file normalize "$origin_dir/hdl/GLITC_clock_generator/GLITC_clock_generator.v"]"\
 "[file normalize "$origin_dir/hdl/dual_RITC_correlator/dual_RITC_correlator_v3.v"]"\
 "[file normalize "$origin_dir/hdl/glitc_intercom/glitc_intercom_v3.v"]"\
 "[file normalize "$origin_dir/ip_cores/glitc_icon/glitc_icon.xco"]"\
 "[file normalize "$origin_dir/ip_cores/glitc_ila/glitc_ila.xco"]"\
 "[file normalize "$origin_dir/ip_cores/glitc_vio/glitc_vio.xco"]"\
 "[file normalize "$origin_dir/hdl/glitc_top_v2.v"]"\
 "[file normalize "$origin_dir/hdl/RITC_dual_phase_scanner/ROM_form.vhd"]"\
 "[file normalize "$origin_dir/hdl/GLITC_external_settings/ROM_form.vhd"]"\
 "[file normalize "$origin_dir/hdl/GLITC_external_settings/opencores_i2c/timescale.v"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hdl/RITC_dual_phase_scanner/ritc_phase_scan_program_V3.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/hdl/GLITC_external_settings/glitc_external_settings_rom.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/hdl/common/kcpsm6.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/hdl/RITC_dual_phase_scanner/ROM_form.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/hdl/GLITC_external_settings/ROM_form.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "glitc_top_v2" $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/constraints/glitc_top_v2.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/constraints/glitc_top_v2.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "top" "glitc_top_v2" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.unifast" "" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7a200tfbg484-2 -flow {Vivado Synthesis 2015} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2015" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property "part" "xc7a200tfbg484-2" $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7a200tfbg484-2 -flow {Vivado Implementation 2015} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2015" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "part" "xc7a200tfbg484-2" $obj
set_property "steps.place_design.args.directive" "ExtraNetDelay_high" $obj
set_property "steps.phys_opt_design.is_enabled" "1" $obj
set_property "steps.phys_opt_design.args.directive" "AggressiveExplore" $obj
set_property "steps.route_design.args.directive" "MoreGlobalIterations" $obj
set_property "steps.post_route_phys_opt_design.is_enabled" "1" $obj
set_property "steps.post_route_phys_opt_design.args.directive" "AggressiveExplore" $obj
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:glitc-project"
